"""Golden feature-resolution snapshot: the proof that a change to the feature catalogue or the
resolver changed nothing it should not have.

Every value a consumer of ``features.registry`` can observe is captured here as data.  The
snapshot is generated from the tree (``python -m features.tests.golden_feature_resolution``)
and compared byte for byte by ``features/tests/test_feature_definition_boundary.py``.

It is deliberately exhaustive rather than representative: the whole point of a registration
boundary is the claim "adding a definition cannot change how an existing binding resolves",
and a sampled fixture cannot carry that claim.

Keying rule (feature promotion, 2026-09): every section is keyed per resolvable NAME.  A
universe (``resolve_source_universe``, ``resolve_feature_instances`` with no instances, the
engine/family alias surfaces, column canonicalisation, study-level derivations) is recorded as
one key per member rather than one digest per list, so that ADDING a definition shows up as
new keys only -- never as a moved digest of an existing key.  ``compare_additive`` is the
mechanical statement of that rule; ``--additive-against <git-ref>`` applies it between the
committed golden at a ref and the tree.  The golden itself stays exact: it is regenerated by
``research feature promote`` (generated output, verified by ``--check``), and a CORE change
that moves an existing binding still has to justify every moved line.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Sequence

GOLDEN_PATH = Path(__file__).resolve().parent / "golden" / "feature_resolution.json"
REPO_ROOT = Path(__file__).resolve().parents[2]


def _definition_record(definition: Any) -> Dict[str, Any]:
    from dataclasses import asdict
    return json.loads(json.dumps(asdict(definition), default=str))


def _call(fn, *args, **kwargs) -> Dict[str, Any]:
    """Record either the return value or the exact fail-closed error."""
    try:
        return {"ok": True, "value": json.loads(json.dumps(fn(*args, **kwargs), default=str))}
    except Exception as exc:          # noqa: BLE001 - the error IS the observable behaviour
        return {"ok": False, "error": f"{type(exc).__name__}: {exc}"}


def _members(prefix: str, result: Dict[str, Any], into: Dict[str, Any]) -> None:
    """Flatten a list-valued call into one key per member (or one key for the error)."""
    if not result.get("ok"):
        into[prefix] = result
        return
    value = result["value"]
    if isinstance(value, list):
        for item in value:
            key = item.get("physical_alias") if isinstance(item, dict) else str(item)
            into[f"{prefix}|{key}"] = item
    elif isinstance(value, dict):
        for k, v in value.items():
            into[f"{prefix}|{k}"] = v
    else:
        into[prefix] = result


def build() -> Dict[str, Any]:
    from features import registry as R
    from features.registry import FeatureInstance

    snapshot: Dict[str, Any] = {"schema_version": 2}

    # ---- the definition catalogues themselves (membership, order, every field) ----------
    snapshot["FEATURE_REGISTRY"] = {name: _definition_record(d) for name, d in R.FEATURE_REGISTRY.items()}
    snapshot["FEATURE_REGISTRY_order"] = list(R.FEATURE_REGISTRY)
    snapshot["CANONICAL_FEATURE_DEFINITIONS"] = {name: _definition_record(d) for name, d in R.CANONICAL_FEATURE_DEFINITIONS.items()}
    snapshot["CANONICAL_FEATURE_DEFINITIONS_order"] = list(R.CANONICAL_FEATURE_DEFINITIONS)
    snapshot["LEGACY_FEATURE_INSTANCE_OVERRIDES"] = {
        alias: {"canonical_name": inst.canonical_name, "parameters": dict(inst.parameters), "physical_alias": inst.physical_alias}
        for alias, inst in R.LEGACY_FEATURE_INSTANCE_OVERRIDES.items()}
    snapshot["LEGACY_FEATURE_INSTANCE_OVERRIDES_order"] = list(R.LEGACY_FEATURE_INSTANCE_OVERRIDES)
    snapshot["_ALIAS_TO_CANONICAL"] = dict(R._ALIAS_TO_CANONICAL)

    # ---- per-canonical-definition resolution ------------------------------------------
    canonical: Dict[str, Any] = {}
    for name in sorted(R.CANONICAL_FEATURE_DEFINITIONS):
        canonical[name] = {
            "status": _call(R.canonical_definition_status, name),
            "request_active": _call(R.resolve_feature_request, name),
            "request_legacy": _call(R.resolve_feature_request, name, authority="legacy"),
            "validate_bare": _call(R.validate_feature_instance, FeatureInstance(name)),
            "alias_bare": _call(R.generate_physical_alias, FeatureInstance(name)),
            "inputs_bare": _call(R.derive_instance_input_requirements, FeatureInstance(name)),
            "compat_keys": _call(R.provider_compatibility_keys, name),
            "runtime_definition": _call(lambda n: _definition_record(R.resolve_runtime_feature_definition(n)), name),
        }
    snapshot["canonical"] = canonical

    # ---- per-legacy-alias resolution (the instance overrides carry real parameters) -----
    legacy: Dict[str, Any] = {}
    for alias in sorted(R.LEGACY_FEATURE_INSTANCE_OVERRIDES):
        inst = R.LEGACY_FEATURE_INSTANCE_OVERRIDES[alias]
        legacy[alias] = {
            "validate": _call(R.validate_feature_instance, inst),
            "alias": _call(R.generate_physical_alias, inst),
            "inputs": _call(R.derive_instance_input_requirements, inst),
            "request_active": _call(R.resolve_feature_request, alias),
            "request_legacy": _call(R.resolve_feature_request, alias, authority="legacy"),
            "instances_active": _call(R.resolve_feature_instances, "canonical_verified_definition_universe", (inst,)),
        }
    snapshot["legacy_instance_overrides"] = legacy

    # ---- every physical-catalogue entry, resolved both ways ----------------------------
    physical: Dict[str, Any] = {}
    for name in sorted(R.FEATURE_REGISTRY):
        physical[name] = {
            "request_active": _call(R.resolve_feature_request, name),
            "request_legacy": _call(R.resolve_feature_request, name, authority="legacy"),
            "resolve_name": _call(R.resolve_feature_name, name),
            "effective_snapshot_anchor": _call(R.effective_snapshot_anchor, name, "golden_study"),
        }
    snapshot["physical_catalogue"] = physical

    # ---- universe / alias surfaces: one key per member ---------------------------------
    sources = [None, "", "canonical_verified_definition_universe", "verified_registry_numeric_universe", "not_a_source"]
    universes: Dict[str, Any] = {}
    for source in sources:
        for authority in ("active", "candidate", "legacy", "bogus"):
            for legacy_mode in (False, True):
                _members(f"{source!r}|{authority}|{legacy_mode}",
                         _call(R.resolve_source_universe, source, authority=authority, legacy_mode=legacy_mode), universes)
    snapshot["source_universes"] = universes
    instances: Dict[str, Any] = {}
    for source in sources:
        for legacy_mode in (False, True):
            _members(f"{source!r}|{legacy_mode}", _call(R.resolve_feature_instances, source, None, legacy_mode=legacy_mode), instances)
    snapshot["feature_instances"] = instances
    runtime_aliases: Dict[str, Any] = {}
    engine_aliases: Dict[str, Any] = {}
    for a in ("active", "candidate", "legacy", "bogus"):
        _members(a, _call(R.resolve_runtime_feature_aliases, authority=a), runtime_aliases)
        _members(a, _call(R.resolve_feature_engine_output_aliases, authority=a), engine_aliases)
    snapshot["runtime_feature_aliases"] = runtime_aliases
    snapshot["engine_output_aliases"] = engine_aliases

    families = sorted({d.family for d in R.FEATURE_REGISTRY.values() if d.family}
                      | {d.family for d in R.CANONICAL_FEATURE_DEFINITIONS.values() if d.family})
    family_aliases: Dict[str, Any] = {}
    for f in families:
        _members(f, _call(R.resolve_runtime_family_aliases, {f}), family_aliases)
    _members("*", _call(R.resolve_runtime_family_aliases, set(families)), family_aliases)
    snapshot["family_aliases"] = family_aliases

    # ---- provider column canonicalisation: every name, one key per column ---------------
    columns = sorted(R.FEATURE_REGISTRY) + sorted(R.CANONICAL_FEATURE_DEFINITIONS) + ["not_a_column"]
    canon: Dict[str, Any] = {}
    _members("columns", _call(R.canonicalize_provider_columns, columns), canon)
    snapshot["canonicalize_provider_columns"] = canon

    # ---- the parameterised surface: every declared parameter value of every definition --
    parameterised: Dict[str, Any] = {}
    for name, definition in sorted(R.CANONICAL_FEATURE_DEFINITIONS.items()):
        cases: List[Dict[str, Any]] = [dict(combo) for combo in (definition.supported_parameter_combinations or ())]
        for key, values in sorted((definition.supported_parameter_values or {}).items()):
            for value in values:
                cases.append({key: value})
        for tf in definition.supported_timeframes or ():
            cases.append({"timeframe": tf})
            cases.append({"timeframe": tf, "bar_state": "forming", "update_every": "1s"})
        cases.append({"bogus_parameter": 1})
        seen = set()
        records = []
        for params in cases:
            key = json.dumps(params, sort_keys=True, default=str)
            if key in seen:
                continue
            seen.add(key)
            inst = FeatureInstance(name, params)
            records.append({"parameters": json.loads(json.dumps(params, default=str)),
                            "validate": _call(R.validate_feature_instance, inst),
                            "alias": _call(R.generate_physical_alias, inst),
                            "inputs": _call(R.derive_instance_input_requirements, inst),
                            "request": _call(R.resolve_feature_request, name, params)})
        parameterised[name] = records
    snapshot["parameterised"] = parameterised

    # ---- study-level derivation (what the collector and the compiler actually call) -----
    class _Spec:
        def __init__(self, instances=None, feature_list=None):
            self.instances = instances
            self.feature_list = feature_list

    derivations: Dict[str, Any] = {
        "empty": _call(R.derive_study_feature_requirements, _Spec()),
        "unknown": _call(R.derive_study_feature_requirements, _Spec(instances=[{"feature": "not_a_feature"}])),
    }
    for alias in sorted(R.LEGACY_FEATURE_INSTANCE_OVERRIDES):
        inst = R.LEGACY_FEATURE_INSTANCE_OVERRIDES[alias]
        derivations[f"legacy_list|{alias}"] = _call(R.derive_study_feature_requirements, _Spec(feature_list=[alias]))
        derivations[f"canonical_parameterised|{alias}"] = _call(
            R.derive_study_feature_requirements,
            _Spec(instances=[{"feature": inst.canonical_name, "parameters": dict(inst.parameters),
                              "physical_alias": inst.physical_alias}]))
    for name in sorted(R.CANONICAL_FEATURE_DEFINITIONS):
        derivations[f"canonical_bare|{name}"] = _call(R.derive_study_feature_requirements, _Spec(instances=[{"feature": name}]))
    snapshot["study_derivations"] = derivations

    # ---- fail-closed cases that are the guard's and the compiler's contract -------------
    snapshot["errors"] = {
        "unknown_canonical": _call(R.resolve_feature_request, "definitely_not_a_feature"),
        "instance_shaped": _call(R.resolve_feature_request, "ema_21_slope"),
        "temporal_shaped": _call(R.resolve_feature_request, "prior_5m_regime_efficiency"),
        "unknown_authority": _call(R.resolve_feature_request, "regime_efficiency", authority="nope"),
        "unknown_parameter": _call(R.validate_feature_instance, FeatureInstance("regime_efficiency", {"nope": 1})),
        "forming_unsupported": _call(R.validate_feature_instance, FeatureInstance("regime_efficiency", {"timeframe": "5m", "bar_state": "forming"})),
        "ambiguous_temporal": _call(R.validate_feature_instance, FeatureInstance("regime_efficiency", {"timeframe": "5m", "update_every": "1s"})),
        "window_and_timeframe": _call(R.validate_feature_instance, FeatureInstance("rolling_giveback_atr", {"window": "300s", "timeframe": "5m", "update_every": "1s"})),
        "bad_duration": _call(R.validate_feature_instance, FeatureInstance("regime_efficiency", {"timeframe": "5x"})),
        "name_embeds_instance": _call(R.validate_canonical_feature_name, R.FeatureDefinition(name="ema_21_slope")),
        "name_clean": _call(R.validate_canonical_feature_name, R.FeatureDefinition(name="regime_efficiency")),
        "bind_unknown_anchor": _call(R.bind_snapshot_anchor, "definitely_not_a_feature", "s", "at_fill_time"),
    }
    return snapshot


def _sha(value: Any) -> str:
    import hashlib
    return hashlib.sha256(json.dumps(value, sort_keys=True, default=str).encode("utf-8")).hexdigest()


# Sections small and diagnostic enough to keep verbatim: when one of these moves, the test
# shows the actual before/after rather than a hash.
_VERBATIM = ("schema_version", "errors", "FEATURE_REGISTRY_order", "CANONICAL_FEATURE_DEFINITIONS_order",
             "LEGACY_FEATURE_INSTANCE_OVERRIDES_order", "_ALIAS_TO_CANONICAL")
_ORDER_SECTIONS = ("FEATURE_REGISTRY_order", "CANONICAL_FEATURE_DEFINITIONS_order", "LEGACY_FEATURE_INSTANCE_OVERRIDES_order")


def manifest(snapshot: Dict[str, Any]) -> Dict[str, Any]:
    """One digest per resolvable name, so a failure names the binding that moved.

    The full snapshot is several MB of resolver output; committing digests keyed by the thing
    that was resolved keeps the fixture reviewable while losing none of its coverage --
    ``--full`` regenerates the whole snapshot for diffing when one of them fails.
    """
    out: Dict[str, Any] = {"verbatim": {k: snapshot[k] for k in _VERBATIM if k in snapshot}}
    digests: Dict[str, Dict[str, str]] = {}
    for section, body in snapshot.items():
        if section in _VERBATIM:
            continue
        if isinstance(body, dict):
            digests[section] = {str(k): _sha(v) for k, v in body.items()}
        else:
            digests[section] = {"": _sha(body)}
    out["digests"] = digests
    out["composite_sha256"] = _sha({"verbatim": out["verbatim"], "digests": digests})
    return out


def _is_subsequence(old: Sequence[Any], new: Sequence[Any]) -> bool:
    it = iter(new)
    return all(any(x == y for y in it) for x in old)


def _key_names(key: str) -> List[str]:
    """The resolvable names a manifest key is about (``section:name`` / ``section:prefix|name``)."""
    body = key.split(":", 1)[1] if ":" in key else key
    return [part for part in body.split("|") if part]


def compare_additive(old: Dict[str, Any], new: Dict[str, Any], *, allowed_names: Sequence[str] = ()) -> Dict[str, Any]:
    """The additive rule between two manifests: everything the old one recorded resolves
    identically in the new one; the new one may only ADD keys (and append to order lists).

    ``allowed_names``: definitions whose OWN keys may move -- the promotion of an already
    declared record turns its resolution from UNVERIFIED into a binding, which is the point.
    No key about any other name may move.

    Returns ``{"additive": bool, "moved": [...], "removed": [...], "added": {section: n}, "allowed_moves": [...]}``.
    """
    moved: List[str] = []
    removed: List[str] = []
    added: Dict[str, int] = {}
    allowed_moves: List[str] = []
    allowed = set(allowed_names)

    def _note_move(key: str) -> None:
        (allowed_moves if allowed and set(_key_names(key)) & allowed else moved).append(key)
    ov, nv = old.get("verbatim", {}), new.get("verbatim", {})
    for key in ov:
        if key in _ORDER_SECTIONS:
            if not _is_subsequence(ov[key], nv.get(key, [])):
                moved.append(f"verbatim:{key} (old order is not a subsequence of the new order)")
            elif len(nv.get(key, [])) != len(ov[key]):
                added[f"verbatim:{key}"] = len(nv[key]) - len(ov[key])
        elif key == "errors" or key == "_ALIAS_TO_CANONICAL":
            o, n = ov[key], nv.get(key, {})
            for k, v in o.items():
                if k not in n:
                    removed.append(f"verbatim:{key}:{k}")
                elif n[k] != v:
                    _note_move(f"verbatim:{key}:{k}")
            extra = len(set(n) - set(o))
            if extra:
                added[f"verbatim:{key}"] = extra
        elif ov[key] != nv.get(key):
            moved.append(f"verbatim:{key}")
    od, nd = old.get("digests", {}), new.get("digests", {})
    for section, entries in od.items():
        current = nd.get(section, {})
        for k, v in entries.items():
            if k not in current:
                removed.append(f"{section}:{k}")
            elif current[k] != v:
                _note_move(f"{section}:{k}")
        extra = len(set(current) - set(entries))
        if extra:
            added[section] = extra
    for section in nd:
        if section not in od:
            added[section] = len(nd[section])
    return {"additive": not moved and not removed, "moved": moved, "removed": removed, "added": added,
            "allowed_moves": allowed_moves}


def write_golden(full: Path | None = None) -> str:
    snapshot = build()
    GOLDEN_PATH.parent.mkdir(parents=True, exist_ok=True)
    GOLDEN_PATH.write_text(json.dumps(manifest(snapshot), indent=1, sort_keys=True) + "\n", encoding="utf-8")
    if full is not None:
        full.parent.mkdir(parents=True, exist_ok=True)
        full.write_text(json.dumps(snapshot, indent=1, sort_keys=True) + "\n", encoding="utf-8")
    return GOLDEN_PATH.relative_to(REPO_ROOT).as_posix()


def _golden_at(ref: str) -> Dict[str, Any]:
    import subprocess
    rel = GOLDEN_PATH.relative_to(REPO_ROOT).as_posix()
    r = subprocess.run(["git", "show", f"{ref}:{rel}"], cwd=str(REPO_ROOT), capture_output=True, text=True, encoding="utf-8")
    if r.returncode != 0:
        raise SystemExit(f"GOLDEN_REF_UNREADABLE: {ref}:{rel}: {r.stderr.strip()}")
    return json.loads(r.stdout)


def main() -> int:
    import argparse
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--full", type=Path, help="also write the whole uncompressed snapshot here (for diffing)")
    ap.add_argument("--check", action="store_true", help="do not write; fail GOLDEN_STALE if the committed fixture disagrees with the tree")
    ap.add_argument("--additive-against", metavar="GIT_REF",
                    help="do not write; compare the committed golden at GIT_REF with the tree under the additive rule")
    ap.add_argument("--allow", action="append", default=[], metavar="NAME",
                    help="definition whose own keys may move (a promotion of an already-declared record)")
    args = ap.parse_args()
    if args.check or args.additive_against:
        current = manifest(build())
        if args.check:
            committed = json.loads(GOLDEN_PATH.read_text(encoding="utf-8")) if GOLDEN_PATH.is_file() else {}
            ok = committed == current
            print(json.dumps({"check": "GOLDEN_CURRENT" if ok else "GOLDEN_STALE", "composite_sha256": current["composite_sha256"]}))
            if not ok:
                return 1
        if args.additive_against:
            verdict = compare_additive(_golden_at(args.additive_against), current, allowed_names=args.allow)
            print(json.dumps({"additive_against": args.additive_against, **verdict, "composite_sha256": current["composite_sha256"]}, indent=1))
            if not verdict["additive"]:
                return 1
        return 0
    rel = write_golden(args.full)
    print(f"wrote {rel} ({GOLDEN_PATH.stat().st_size} bytes)")
    if args.full:
        print(f"wrote {args.full} ({args.full.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
