"""Auto-Generated Deterministic Study Contract Tests.
===================================================
Derived from study.yaml (SHA-256: 28d7506daf62a7c495d874d4b0e87146d237073a5d1369eb050c2bd5021c1453).

Generated by scripts/create_study.py. Every assertion below reads an artifact from disk
and compares it against an independently recomputed value. Nothing is compared to a baked
literal on both sides -- a generated test that cannot fail is worse than no test, because
it reports coverage it does not provide.
"""

import hashlib
import json
from pathlib import Path

import pytest
import yaml

STUDY_DIR = Path(__file__).resolve().parents[1]

# The repository root is located by walking up from this file until a marker is found,
# then falling back to the installed package location. Deriving it positionally
# (STUDY_DIR.parents[1]) breaks whenever a study is scaffolded outside studies/ -- the
# tests then silently resolve module paths inside a temp directory.
def _repo_root() -> Path:
    for candidate in [STUDY_DIR, *STUDY_DIR.parents]:
        if (candidate / "features" / "registry.py").exists() and (candidate / "research").is_dir():
            return candidate
    import features
    return Path(features.__file__).resolve().parents[1]


REPO_ROOT = _repo_root()


def _study_yaml():
    return yaml.safe_load((STUDY_DIR / "study.yaml").read_text(encoding="utf-8"))


def _compiled():
    return json.loads((STUDY_DIR / "compiled_study.json").read_text(encoding="utf-8"))


def _config(name):
    return json.loads((STUDY_DIR / "config" / f"{name}.json").read_text(encoding="utf-8"))


def test_runtime_is_nautilustrader_in_every_authority():
    """The runtime declared by study.yaml, the compiled spec and the execution contract agree."""
    assert _study_yaml()["execution"]["runtime"] == "nautilustrader"
    assert _compiled()["spec"]["execution"]["runtime"] == "nautilustrader"
    assert _config("execution_contract")["runtime"] == "nautilustrader"


def test_compiled_spec_hash_matches_recomputed_spec_hash():
    """compiled_study.json's spec_sha256 is reproducible from the spec it contains."""
    import sys
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    from research.schemas.study_spec import StudySpec

    compiled = _compiled()
    respec = StudySpec.model_validate(_study_yaml())
    assert respec.compute_sha256() == compiled["spec_sha256"], (
        "study.yaml no longer compiles to the spec hash recorded in compiled_study.json"
    )


def test_feature_hash_equals_hash_recomputed_from_the_ordered_list():
    """The frozen feature hash is derived from the declared ordered list, not asserted."""
    fc = _config("feature_contract")
    declared = fc["feature_list"] or []
    recomputed = hashlib.sha256(json.dumps(declared).encode("utf-8")).hexdigest()
    assert fc["feature_list_sha256"] == recomputed
    assert fc["feature_count"] == len(declared)
    # When study.yaml declares features via `instances`, the compiler echoes the
    # resolved ordered list onto StudySpec.features.feature_list. A train-only
    # candidate-universe study legitimately leaves it None. Compare only when set.
    spec_feature_list = _compiled()["spec"]["features"].get("feature_list")
    if spec_feature_list is not None:
        assert spec_feature_list == declared


def test_declared_features_resolve_in_the_central_registry():
    """Every declared feature binds to a real registry entry with a real implementation."""
    import sys
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    from features.registry import resolve_feature_request

    fc = _config("feature_contract")
    # `feature_list` entries are rendered physical output columns; the canonical
    # identity to resolve is (canonical_name, parameters) from resolved_feature_instances.
    resolved_instances = fc.get("resolved_feature_instances")
    if resolved_instances:
        items = [(r["canonical_name"], r.get("parameters") or {}) for r in resolved_instances]
    else:
        items = [(n, {}) for n in (fc.get("feature_list") or [])]
    import importlib
    for canonical, params in items:
        resolved = resolve_feature_request(canonical, params)
        impl = resolved["provider"]
        assert impl, f"{canonical!r} has no implementation binding"
        module_name = impl.rsplit(".", 1)[0]
        mod = importlib.import_module(module_name)
        assert Path(mod.__file__).exists(), (
            f"{canonical!r} implementation module {module_name} does not resolve to a file"
        )


def test_population_contract_matches_the_authoritative_study_population():
    """The compiled population contract equals what study.yaml declares."""
    y = _study_yaml()["population"]
    pc = _config("population_contract")
    assert pc["prevailing_regime"] == y.get("prevailing_regime")
    assert pc["session"] == y.get("session")
    assert pc["population_type"] == y.get("type")
    assert _compiled()["spec"]["population"]["session"] == pc["session"]


def test_session_resolves_to_an_explicit_window():
    """`RTH` is not self-explanatory; it must resolve to concrete boundaries."""
    import sys
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    from utils.session_boundaries import resolve_session_window

    session = _config("population_contract")["session"]
    start, end = resolve_session_window(session)
    assert start < end


def test_target_contract_fields_equal_the_compiled_target():
    """Target fields agree across study.yaml, the compiled spec and the config contract."""
    y = _study_yaml()["target"]
    tc = _config("target_contract")
    # A `flip` target authors horizon_seconds directly. A composite ordered-barrier
    # target carries it on its single forward outcome; the compiler surfaces that one
    # value onto target_contract.horizon_seconds. Either way the contract must equal it.
    fo_horizons = {fo.get("horizon_seconds") for fo in (tc.get("required_forward_outcomes") or [])}
    fo_horizons.discard(None)
    if y.get("horizon_seconds") is not None:
        expected_h = y["horizon_seconds"]
    elif len(fo_horizons) == 1:
        expected_h = next(iter(fo_horizons))
    else:
        expected_h = None
    assert tc["horizon_seconds"] == expected_h
    assert tc["direction"] == y.get("direction")
    assert tc["event"] == (y.get("event") or "regime_flip")
    compiled_h = _compiled()["spec"]["target"].get("horizon_seconds")
    if compiled_h is not None:
        assert compiled_h == tc["horizon_seconds"]


def test_censoring_policy_is_declared_and_bounded_by_the_horizon():
    """A declared censoring policy must be internally consistent with the horizon."""
    tc = _config("target_contract")
    policy = tc.get("censoring_policy")
    assert policy is not None, "target contract declares no censoring policy"
    # The censoring bound is the effective horizon (legacy default 300 when a target
    # declares none anywhere).
    assert policy["max_horizon_seconds"] == (tc["horizon_seconds"] or 300)


def test_execution_chronology_equals_the_source_decision():
    """The compiled chronology equals study.yaml's, and the partitions stay disjoint."""
    y = _study_yaml()["chronology"]
    ec = _config("execution_contract")["chronology"]
    assert ec["train"] == (y.get("train") or [])
    assert ec["dev"] == (y.get("dev") or [])
    assert ec["prohibited"] == (y.get("prohibited") or [])
    assert set(ec["train"]).isdisjoint(ec["dev"])
    assert set(ec["train"]).isdisjoint(ec["prohibited"])
    assert set(ec["dev"]).isdisjoint(ec["prohibited"])


def test_timestamp_evidence_is_measured_on_this_study_instrument():
    """The timestamp contract must carry this instrument's own empirical measurements."""
    symbol = _study_yaml()["instrument"]["symbol"].upper()
    tsc = _config("timestamp_contract")
    measurement = tsc["nautilus_catalog"]["empirical_measurement"]
    assert measurement["status"] == "MEASURED"
    measured = measurement["measurements"]
    assert measured, "no bar-timestamp measurements were recorded"
    for bar_type, rec in measured.items():
        assert bar_type.upper().startswith(symbol + "."), (
            f"timestamp evidence for {bar_type} does not belong to instrument {symbol}"
        )
        assert rec["pass"] is True
        assert rec["observed_deltas_ns"] == [rec["expected_delta_ns"]]


def test_deliverables_are_declared_per_mode_and_all_reachable():
    """Every declared deliverable maps to a producer in a mode this study may run."""
    import sys
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    from research.engines.deliverables_engine import KNOWN_ARTIFACT_PRODUCERS, artifact_modes

    dc = _config("deliverables_contract")
    assert dc["authorized_modes"], "no authorized modes declared"
    for mode, artifacts in dc["deliverables_by_mode"].items():
        assert mode in dc["authorized_modes"]
        assert artifacts, f"mode {mode} declares no deliverables"
        for a in artifacts:
            assert a in KNOWN_ARTIFACT_PRODUCERS, f"{a} has no known producer"
            assert mode in artifact_modes(a), (
                f"{a} is declared under {mode} but produced by {artifact_modes(a)}"
            )


def test_spec_md_renders_the_deliverables_contract():
    """SPEC prose and the machine-readable contract cannot drift apart."""
    spec_md = (STUDY_DIR / "SPEC.md").read_text(encoding="utf-8")
    dc = _config("deliverables_contract")
    for artifacts in dc["deliverables_by_mode"].values():
        for a in artifacts:
            assert a in spec_md, f"deliverable {a} is in the contract but not in SPEC.md"
