#!/usr/bin/env python3
"""Golden end-to-end fixture: two synthetic trading days, SYN_A (execution) + SYN_B (context).

Scenarios (each with an expected row or event):
  sparse 1s with deliberate no-print seconds (grid index skipped, bucket incompleteness),
  1m + derived 5s/5m, an early-close session edge, a same-timestamp cross-stream event,
  a watch that expires, a watch that triggers, two simultaneous triggers (precedence),
  same-bar stop+target touch, timeout, session censor, data-end censor, and add-to-winner
  (a typed capability gap in this phase: the trade sink is out of scope).

Expected outputs are generated by INDEPENDENT straight-line evaluators in this file
(written from the contract text, sharing no code with the host).  The replay oracle
(``research_workflow.target_replay_oracle``) is applied on top by the test.

    python fixtures/golden/build_golden_fixture.py     # rewrites fixtures/golden/{bars,expected}.json
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parent
NS = 1_000_000_000
D1 = 1_893_369_600  # 2030-01-07 00:00:00 UTC (Monday), seconds
D2 = D1 + 86_400
LEVEL_A = 100.0       # SYN_A regime level (1m close above -> +1)
LEVEL_5S = 100.5      # SYN_A 5s regime level
LEVEL_B = 50.0        # SYN_B regime level
ATR = 2.0             # constant ATR (points)
HORIZON_S = 60
GRID_S = 5
MAX_AGE_S = 600
MAX_AGE_FLIP_S = 900
AGE_GATE_S = 10

# session rows (open, close] in seconds: D1 09:00-16:00, D2 09:00-12:58 (early close)
SESSIONS = [(D1 + 9 * 3600, D1 + 16 * 3600), (D2 + 9 * 3600, D2 + 12 * 3600 + 58 * 60)]


# --------------------------------------------------------------------------- #
# price script
# --------------------------------------------------------------------------- #
def _seg(out: Dict[int, Tuple[float, float, float, float]], start: int, end: int, price: float,
         skip: Tuple[int, ...] = ()) -> None:
    """Flat segment [start, end) at ``price`` (o=h=l=c), skipping the listed seconds."""
    for s in range(start, end):
        if s in skip:
            continue
        out[s] = (price, price, price, price)


def build_syn_a_1s() -> Dict[int, Tuple[float, float, float, float]]:
    p: Dict[int, Tuple[float, float, float, float]] = {}
    h = lambda hh, mm=0, ss=0, day=D1: day + hh * 3600 + mm * 60 + ss
    # D1 warmup 08:50-09:00 at 99 (regime -1)
    _seg(p, h(8, 50), h(9, 0), 99.0)
    # 09:00:00-09:01:30 at 101 (1m close 101 at 09:01:00 -> regime +1); sparse: 09:01:15 and 09:01:16 missing
    _seg(p, h(9, 0), h(9, 1, 31), 101.0, skip=(h(9, 1, 14), h(9, 1, 15)))
    # 09:01:31 target touch bar
    p[h(9, 1, 31)] = (101.0, 103.25, 101.0, 103.0)
    _seg(p, h(9, 1, 32), h(9, 2, 1), 103.0)
    # 09:02:01 same-bar stop + target touch (both barriers of every pending +1 candidate)
    p[h(9, 2, 1)] = (103.0, 105.5, 100.75, 103.0)
    _seg(p, h(9, 2, 2), h(9, 3, 0), 103.0)
    # 09:03:00-09:03:30 dip to 99 (watch enters; 5s turns opposite); 09:03:31 recovery to 101.5
    _seg(p, h(9, 3, 0), h(9, 3, 31), 99.0)
    _seg(p, h(9, 3, 31), h(9, 4, 30), 101.5)
    # 09:04:30 onwards 104 (positive for the watch entry at 09:03:35)
    _seg(p, h(9, 4, 30), h(9, 6, 0), 104.0)
    # 09:06:00-09:06:40 dip to 100.75 (watch enters, never arms, expires by age); then 104.5
    _seg(p, h(9, 6, 0), h(9, 7, 1), 100.25)   # 1m closes stay above the 100 level (no flip); 5s dir -1 below 100.5
    _seg(p, h(9, 7, 1), h(9, 12, 0), 104.5)
    # quiet until 15:39
    _seg(p, h(9, 12), h(15, 39), 104.5)
    # 15:39 minute closes 101 -> already +1; keep 101 until 15:54; 15:54 minute at 99 -> regime -1 at 15:55:00
    _seg(p, h(15, 39), h(15, 54), 101.0)
    _seg(p, h(15, 54), h(16, 5), 99.0)
    # D2: 08:50-12:47 at 99 (regime stays -1, aged out); 12:47 minute at 101 -> +1 at 12:48:00; data ends 12:57:30
    _seg(p, h(8, 50, day=D2), h(12, 47, day=D2), 99.0)
    _seg(p, h(12, 47, day=D2), h(12, 57, 30, day=D2), 101.0)
    return p


def aggregate_1m(one_s: Dict[int, Tuple[float, float, float, float]]) -> Dict[int, Tuple[float, float, float, float]]:
    out: Dict[int, Tuple[float, float, float, float]] = {}
    for s in sorted(one_s):
        m = (s // 60) * 60
        o, hh, ll, c = one_s[s]
        if m not in out:
            out[m] = (o, hh, ll, c)
        else:
            po, ph, pl, _ = out[m]
            out[m] = (po, max(ph, hh), min(pl, ll), c)
    return out


def build_syn_b_1m() -> Dict[int, float]:
    """SYN_B 1m closes: 49 (dir -1) until the bar closing at 09:01:00 D1 (close 51, dir +1); back to 49 at 09:10."""
    out: Dict[int, float] = {}
    for day in (D1, D2):
        for m in range(day + 8 * 3600 + 50 * 60, day + 16 * 3600 + 5 * 60, 60):
            out[m] = 49.0
    flip_bar = D1 + 9 * 3600  # ts_event 09:00:00 -> ts_init 09:01:00 (same instant as SYN_A's regime start)
    out[flip_bar] = 51.0
    for m in range(D1 + 9 * 3600 + 60, D1 + 9 * 3600 + 9 * 60, 60):
        out[m] = 51.0
    return out


# --------------------------------------------------------------------------- #
# independent evaluators
# --------------------------------------------------------------------------- #
def regimes_1m(one_m: Dict[int, Tuple[float, float, float, float]], level: float) -> List[Tuple[int, int, float]]:
    """[(start_ts_init, dir, start_price)] -- a change of direction at a completed 1m bar."""
    out = []
    cur = 0
    for m in sorted(one_m):
        o, _, _, c = one_m[m]
        d = 1 if c > level else -1
        if d != cur:
            out.append((m + 60, d, o))
            cur = d
    return out


def in_session(ts: int) -> bool:
    return any(a < ts <= b for a, b in SESSIONS)


def session_close(ts: int) -> Optional[int]:
    for a, b in SESSIONS:
        if a < ts <= b:
            return b
    for a, b in SESSIONS:
        if ts <= a:
            return b
    return None


def grid_candidates(regimes, one_s, max_age: int) -> List[dict]:
    """Every grid epoch T = start + (k+1)*5s that lands on a printed second, in session, age >= gate."""
    out = []
    bounds = [(r[0], regimes[i + 1][0] if i + 1 < len(regimes) else 10 ** 12) for i, r in enumerate(regimes)]
    for (start, d, sp), (_, nxt) in zip(regimes, bounds):
        k = 0
        while True:
            T = start + (k + 1) * GRID_S
            if T - start > max_age:
                break
            # the regime is current for 1s bars with ts_init < nxt, plus the 1s bar AT nxt (delivered before the 1m flip)
            if T > nxt:
                break
            if (T - 1) in one_s:  # a 1s bar with ts_init == T exists (ts_event = T-1)
                if in_session(T) and (T - start) >= AGE_GATE_S:
                    out.append({"observation_ts": T, "regime_start_ns": start, "checkpoint_index": k, "direction": d,
                                "price": one_s[T - 1][3]})
            k += 1
    return out


def barrier_outcome(T: int, direction: int, one_s, fav: float, adv: float, last_ts: int) -> Tuple[str, Optional[str], Optional[int], Optional[float]]:
    """(disposition, censor_reason, resolved_at, resolution_seconds) for one arm (ATR constant)."""
    seconds = sorted(s + 1 for s in one_s if s + 1 > T)  # ts_init values strictly after T
    if not seconds:
        return "CENSORED", "DATA_END", last_ts, HORIZON_S
    entry_bar = seconds[0]
    entry_price = one_s[entry_bar - 1][0]
    entry_ts = entry_bar - 1
    end = entry_ts + HORIZON_S
    close = session_close(T)
    if close is not None and end > close:
        return "CENSORED", "SESSION_END", close, close - entry_ts
    good = entry_price + direction * fav * ATR
    bad = entry_price - direction * adv * ATR
    for ts in seconds:
        if ts > end:
            break
        _, hi, lo, _ = one_s[ts - 1]
        hit_good = hi >= good if direction > 0 else lo <= good
        hit_bad = lo <= bad if direction > 0 else hi >= bad
        if hit_good and hit_bad:
            return "CENSORED", "AMBIGUOUS_SAME_BAR_TOUCH", ts, ts - entry_ts
        if hit_good:
            return "POSITIVE", None, ts, ts - entry_ts
        if hit_bad:
            return "NEGATIVE", None, ts, ts - entry_ts
    if last_ts >= end:
        return "CENSORED", "TIMEOUT", end, HORIZON_S
    return "CENSORED", "DATA_END", last_ts, HORIZON_S


def flip_outcome(T: int, direction: int, flips: List[Tuple[int, int]], last_ts: int) -> Tuple[str, Optional[str], Optional[int], Optional[int]]:
    """Legacy flip label: a flip to -direction with T <= flip_ts <= T+H is POSITIVE (resolved at flip);
    horizon past the session close -> SESSION_END; else NEGATIVE at the horizon end."""
    end = T + HORIZON_S
    close = session_close(T)
    for fts, fdir in flips:
        if fts < T:
            continue
        if fdir != -direction:
            continue
        if close is not None and end > close:
            # resolved at the flip only if the flip lands before the horizon sweep would have
            return "CENSORED", "SESSION_END", (fts if fts <= end else None), None
        if fts <= end:
            return "POSITIVE", None, fts, fts
        return "NEGATIVE", None, end, None
    if close is not None and end > close:
        return "CENSORED", "SESSION_END", None, None  # resolved at the sweeping bar / run end (not asserted)
    if last_ts >= end:
        return "NEGATIVE", None, end, None
    return "CENSORED", "DATA_END", last_ts, None


def main() -> int:
    one_s = build_syn_a_1s()
    one_m = aggregate_1m(one_s)
    syn_b = build_syn_b_1m()
    bars = []
    for s in sorted(one_s):
        o, hh, ll, c = one_s[s]
        bars.append({"stream": "syn_a_1s", "ts_event": s * NS, "ts_init": (s + 1) * NS, "open": o, "high": hh, "low": ll, "close": c, "volume": 1.0})
    for m in sorted(one_m):
        o, hh, ll, c = one_m[m]
        bars.append({"stream": "syn_a_1m", "ts_event": m * NS, "ts_init": (m + 60) * NS, "open": o, "high": hh, "low": ll, "close": c, "volume": 60.0})
    for m in sorted(syn_b):
        c = syn_b[m]
        bars.append({"stream": "syn_b_1m", "ts_event": m * NS, "ts_init": (m + 60) * NS, "open": c, "high": c, "low": c, "close": c, "volume": 1.0})
    last_ts = max(s + 1 for s in one_s)

    regimes = regimes_1m(one_m, LEVEL_A)
    flips = [(start, d) for start, d, _ in regimes[1:]]  # 0 -> dir is not a flip
    # SYN_B regime timeline for the context-direction column: dir at each 1m close (ts_init), visible strictly before T
    b_changes = []
    cur = 0
    for m in sorted(syn_b):
        d = 1 if syn_b[m] > LEVEL_B else -1
        if d != cur:
            b_changes.append((m + 60, d)); cur = d

    def ctx_dir_at(T: int) -> int:
        d = 0
        for ts, dd in b_changes:
            if ts < T:
                d = dd
        return d

    # barrier plan: two arms, primary tp1_sl1
    cands = grid_candidates(regimes, one_s, MAX_AGE_S)
    expected_barrier = []
    for c in cands:
        a = barrier_outcome(c["observation_ts"], c["direction"], one_s, 1.0, 1.0, last_ts)
        b = barrier_outcome(c["observation_ts"], c["direction"], one_s, 1.0, 0.5, last_ts)
        expected_barrier.append({**c, "f_ctx_dir": ctx_dir_at(c["observation_ts"]),
                                 "arm_a": {"disposition": a[0], "censor_reason": a[1], "resolved_at": a[2], "resolution_seconds": a[3]},
                                 "arm_b": {"disposition": b[0], "censor_reason": b[1], "resolved_at": b[2], "resolution_seconds": b[3]}})
    # flip plan: same grid with max age 900, legacy flip label
    cands_flip = grid_candidates(regimes, one_s, MAX_AGE_FLIP_S)
    expected_flip = []
    for c in cands_flip:
        f = flip_outcome(c["observation_ts"], c["direction"], flips, last_ts)
        expected_flip.append({**c, "disposition": f[0], "censor_reason": f[1], "resolved_at": f[2], "flip_ts": f[3]})

    h = lambda hh, mm=0, ss=0, day=D1: (day + hh * 3600 + mm * 60 + ss)
    # watch plan expected ledger (hand-derived; see docstring scenarios)
    expected_watch = {
        # threshold 2.5 ATR = 5 points below the running favorable extreme (105.5 after the 09:02:01 bar)
        "ledger": [
            {"ts": h(9, 3, 1), "kind": "enter", "state": "WATCH"},      # first 1s bar of the 99 dip: depth 3.25
            {"ts": h(9, 3, 5), "kind": "enter", "state": "ARMED_A"},    # 5s bucket [09:03:00,09:03:05) closes 99 -> 5s dir -1; ARMED_B loses precedence
            {"ts": h(9, 3, 35), "kind": "entry", "state": "ARMED_A"},   # 5s bucket [09:03:30,09:03:35) closes 101.5 -> turned to +1
            {"ts": h(9, 4, 2), "kind": "expire", "state": "WATCH"},     # age(WATCH) = 61s > 60s -> every active state expires
            {"ts": h(9, 4, 2), "kind": "expire", "state": "ARMED_A"},
            {"ts": h(9, 6, 1), "kind": "enter", "state": "WATCH"},      # dip to 100.25: depth 2.625
            {"ts": h(9, 6, 5), "kind": "enter", "state": "ARMED_A"},    # 5s dir -1
            {"ts": h(9, 7, 2), "kind": "expire", "state": "WATCH"},     # age 61s, no turn -> the watch expires without triggering
            {"ts": h(9, 7, 2), "kind": "expire", "state": "ARMED_A"},
            {"ts": h(15, 54, 1), "kind": "enter", "state": "WATCH"},    # 15:54 drop to 99: depth (105.5-99)/2 = 3.25 in the day-long +1 regime
            {"ts": h(15, 54, 5), "kind": "enter", "state": "ARMED_A"},  # 5s dir -1
            {"ts": h(15, 55, 1), "kind": "expire", "state": "WATCH"},   # regime flips to -1 at 15:55:00 -> reset at the next epoch
            {"ts": h(15, 55, 1), "kind": "expire", "state": "ARMED_A"},
        ],
        "candidates": [{"observation_ts": h(9, 3, 35), "regime_start_ns": h(9, 1, 0), "checkpoint_index": 0, "direction": 1,
                        "disposition": "LABELED_POSITIVE", "resolved_at": h(9, 4, 31)}],
    }
    expected = {
        "seconds_base": {"D1": D1, "D2": D2}, "sessions": SESSIONS, "atr": ATR, "horizon_s": HORIZON_S,
        "regimes": [{"start": s, "dir": d, "start_price": p} for s, d, p in regimes],
        "syn_b_changes": b_changes, "last_ts": last_ts,
        "barrier": expected_barrier, "flip": expected_flip, "watch": expected_watch,
        "counts": {"bars_1s": sum(1 for b in bars if b["stream"] == "syn_a_1s"), "bars_1m": sum(1 for b in bars if b["stream"] == "syn_a_1m"),
                   "bars_b_1m": sum(1 for b in bars if b["stream"] == "syn_b_1m"), "barrier_candidates": len(expected_barrier),
                   "flip_candidates": len(expected_flip)},
        "spot_checks": {
            "skipped_grid_index": {"regime_start": h(9, 1, 0), "index": 2, "T": h(9, 1, 15)},
            "same_bar_touch_bar_ts": h(9, 2, 2),
            "same_timestamp_ctx": {"T": h(9, 1, 0), "expected_ctx_dir": -1, "next_T": h(9, 1, 10), "expected_ctx_dir_next": 1},
            "early_close": {"first_session_end_T": h(12, 57, 5, D2), "data_end_first_T": h(12, 56, 35, D2)},
            "d1_session_end_first_T": h(15, 59, 5),
        },
    }
    (OUT / "bars.json").write_text(json.dumps(bars), encoding="utf-8")
    (OUT / "expected.json").write_text(json.dumps(expected, indent=1), encoding="utf-8")
    print(json.dumps(expected["counts"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
