"""Immutable proposed-entry and forward-observation contracts.

The separation this module enforces is the whole point of the package:

* a :class:`ProposedEntry` is decided at ``decision_ts`` and executed at ``entry_ts``
  using only information available then.  Nothing that happens afterwards may change
  whether the entry exists, when it exists, or at what price it is anchored.
* a :class:`ForwardOutcomeSpec` declares -- before any outcome is computed -- which
  future-path quantities will be measured and under which conventions.

Because the spec is frozen and hashed, the output schema is *derived* from it rather
than hand-maintained.  A column that is not generated by :func:`build_outcome_columns`
is not a forward outcome, and every column that is generated by it is post-event data
that must never re-enter a causal feature surface (see ``guard.py``).
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from enum import Enum
import re
from typing import Any, Iterable, Mapping, Optional, Tuple

from research.analysis.identity import canonical_sha256

NS = 1_000_000_000


class ForwardOutcomeError(RuntimeError):
    """Raised when an entry, spec, or observation violates its declared contract."""


class Direction(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"

    @property
    def sign(self) -> int:
        return 1 if self is Direction.LONG else -1


class OutcomeStatus(str, Enum):
    """Terminal status of one forward observation, or of one horizon within it."""

    RESOLVED = "RESOLVED"
    CENSORED_SESSION = "CENSORED_SESSION"
    CENSORED_HORIZON = "CENSORED_HORIZON"
    CENSORED_DATA_END = "CENSORED_DATA_END"
    MISSING_DATA = "MISSING_DATA"


# Severity ordering. A record's overall status is the worst status any of its parts
# reached, so a path with one unobservable horizon can never be reported as RESOLVED.
_STATUS_SEVERITY = {
    OutcomeStatus.RESOLVED: 0,
    OutcomeStatus.CENSORED_SESSION: 1,
    OutcomeStatus.CENSORED_HORIZON: 2,
    OutcomeStatus.CENSORED_DATA_END: 3,
    OutcomeStatus.MISSING_DATA: 4,
}


def worst_status(statuses: Iterable[OutcomeStatus]) -> OutcomeStatus:
    worst = OutcomeStatus.RESOLVED
    for status in statuses:
        if _STATUS_SEVERITY[status] > _STATUS_SEVERITY[worst]:
            worst = status
    return worst


class ReferencePrice(str, Enum):
    """Declared execution-price convention.

    Only conventions our bar data can represent exactly are available. There is no fill
    simulation here: a convention names a price that physically exists on a bar the
    entry was entitled to see (or, for ``CONFIRMATION_CLOSE``, on the confirming bar),
    never a modelled fill.
    """

    DECISION_CLOSE = "DECISION_CLOSE"            # close of the bar that produced the decision
    NEXT_BAR_OPEN = "NEXT_BAR_OPEN"              # open of the first bar after the decision
    CONFIRMATION_CLOSE = "CONFIRMATION_CLOSE"    # close of the confirming bar
    EXPLICIT = "EXPLICIT"                        # caller-supplied; provenance recorded upstream


class BarInclusion(str, Enum):
    """Which bars count as *after* the entry.

    ``FULLY_FORWARD`` (default) admits a bar only when its whole interval lies at or
    after ``entry_ts``. A bar straddling the entry contains price action from before the
    entry, and letting it into an excursion is how a favourable-excursion number quietly
    acquires pre-entry information.
    """

    FULLY_FORWARD = "FULLY_FORWARD"
    CLOSE_AFTER_ENTRY = "CLOSE_AFTER_ENTRY"


class OrderedBarrierDisposition(str, Enum):
    """Terminal result of an asymmetric, direction-normalized barrier race."""

    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    TIMEOUT = "TIMEOUT"
    AMBIGUOUS_FIRST_TOUCH = "AMBIGUOUS_FIRST_TOUCH"
    CENSORED = "CENSORED"


@dataclass(frozen=True)
class OrderedBarrierSpec:
    """One generic favourable-X/adverse-Y race over a fixed forward horizon."""

    barrier_id: str
    favorable_atr: float
    adverse_atr: float
    horizon_seconds: int

    def __post_init__(self) -> None:
        if not re.fullmatch(r"[a-z][a-z0-9_]*", self.barrier_id):
            raise ForwardOutcomeError(
                "ordered barrier_id must match [a-z][a-z0-9_]*"
            )
        if float(self.favorable_atr) <= 0 or float(self.adverse_atr) <= 0:
            raise ForwardOutcomeError("ordered barrier distances must be positive")
        if int(self.horizon_seconds) <= 0:
            raise ForwardOutcomeError("ordered barrier horizon_seconds must be positive")
        object.__setattr__(self, "favorable_atr", float(self.favorable_atr))
        object.__setattr__(self, "adverse_atr", float(self.adverse_atr))
        object.__setattr__(self, "horizon_seconds", int(self.horizon_seconds))

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class ConfirmationSpec:
    """Optional second event on the path between prediction and economic exposure.

    A prediction and its execution need not coincide. When a confirmation is declared,
    the observation is split at ``confirmation_ts`` so that "what the path did while we
    waited" and "what the path did once the thesis confirmed" are separate measurements
    instead of one pooled number.
    """

    confirmation_id: str
    max_wait_seconds: int
    post_max_tracking_seconds: int
    post_horizons_seconds: Tuple[int, ...] = ()
    reference_price: ReferencePrice = ReferencePrice.CONFIRMATION_CLOSE

    def __post_init__(self) -> None:
        if self.max_wait_seconds <= 0:
            raise ForwardOutcomeError("confirmation max_wait_seconds must be positive")
        if self.post_max_tracking_seconds <= 0:
            raise ForwardOutcomeError("confirmation post_max_tracking_seconds must be positive")
        horizons = tuple(sorted({int(h) for h in self.post_horizons_seconds}))
        if any(h <= 0 for h in horizons):
            raise ForwardOutcomeError("post_horizons_seconds must be positive")
        if horizons and horizons[-1] > self.post_max_tracking_seconds:
            raise ForwardOutcomeError("post_horizons_seconds exceed post_max_tracking_seconds")
        object.__setattr__(self, "post_horizons_seconds", horizons)
        object.__setattr__(self, "reference_price", ReferencePrice(self.reference_price))

    def to_dict(self) -> dict[str, Any]:
        body = asdict(self)
        body["reference_price"] = self.reference_price.value
        body["post_horizons_seconds"] = list(self.post_horizons_seconds)
        return body


@dataclass(frozen=True)
class ForwardOutcomeSpec:
    """Declarative description of the future-path measurement.

    Everything the observation layer is allowed to do is stated here and hashed into
    ``spec_sha256``. Horizons, units, censoring and confirmation handling are study
    inputs; the framework contributes no defaults that encode a particular study.
    """

    spec_id: str
    horizons_seconds: Tuple[int, ...]
    max_tracking_seconds: int
    excursion_units: Tuple[str, ...] = ("points", "atr")
    tick_size: Optional[float] = None
    reference_price: ReferencePrice = ReferencePrice.DECISION_CLOSE
    bar_inclusion: BarInclusion = BarInclusion.FULLY_FORWARD
    session: str = "ALL"
    session_end_censoring: bool = False
    max_gap_seconds: Optional[int] = None
    path_quality: bool = True
    epsilon: float = 1e-9
    diagnostic_levels_atr: Tuple[float, ...] = ()
    ordered_barriers: Tuple[OrderedBarrierSpec, ...] = ()
    confirmation: Optional[ConfirmationSpec] = None
    direction_convention: str = "SIGNED_BY_DIRECTION"

    VALID_UNITS = ("points", "atr", "ticks")

    def __post_init__(self) -> None:
        horizons = tuple(sorted({int(h) for h in self.horizons_seconds}))
        if not horizons:
            raise ForwardOutcomeError("at least one horizon is required")
        if any(h <= 0 for h in horizons):
            raise ForwardOutcomeError("horizons_seconds must be positive")
        if int(self.max_tracking_seconds) <= 0:
            raise ForwardOutcomeError("max_tracking_seconds must be positive")
        if horizons[-1] > int(self.max_tracking_seconds):
            raise ForwardOutcomeError(
                f"horizon {horizons[-1]}s exceeds max_tracking_seconds "
                f"{self.max_tracking_seconds}s; the framework does not silently shorten a horizon"
            )
        units = tuple(dict.fromkeys(str(u) for u in self.excursion_units))
        unknown = [u for u in units if u not in self.VALID_UNITS]
        if unknown:
            raise ForwardOutcomeError(f"unknown excursion units: {unknown}")
        if "ticks" in units and not self.tick_size:
            raise ForwardOutcomeError("excursion unit 'ticks' requires tick_size")
        if self.epsilon <= 0:
            raise ForwardOutcomeError("epsilon must be positive")
        if self.direction_convention != "SIGNED_BY_DIRECTION":
            raise ForwardOutcomeError(
                f"unsupported direction_convention: {self.direction_convention!r}"
            )
        levels = tuple(sorted({float(v) for v in self.diagnostic_levels_atr}))
        if any(v <= 0 for v in levels):
            raise ForwardOutcomeError("diagnostic_levels_atr must be positive")
        if levels and "atr" not in units:
            raise ForwardOutcomeError("diagnostic_levels_atr require the 'atr' excursion unit")
        barriers = tuple(
            b if isinstance(b, OrderedBarrierSpec) else OrderedBarrierSpec(**b)
            for b in self.ordered_barriers
        )
        barrier_ids = [b.barrier_id for b in barriers]
        if len(barrier_ids) != len(set(barrier_ids)):
            raise ForwardOutcomeError(f"duplicate ordered barrier ids: {barrier_ids}")
        if any(b.horizon_seconds > int(self.max_tracking_seconds) for b in barriers):
            raise ForwardOutcomeError(
                "ordered barrier horizon_seconds exceed max_tracking_seconds"
            )
        if barriers and "atr" not in units:
            raise ForwardOutcomeError("ordered barriers require the 'atr' excursion unit")
        object.__setattr__(self, "horizons_seconds", horizons)
        object.__setattr__(self, "max_tracking_seconds", int(self.max_tracking_seconds))
        object.__setattr__(self, "excursion_units", units)
        object.__setattr__(self, "diagnostic_levels_atr", levels)
        object.__setattr__(self, "ordered_barriers", barriers)
        object.__setattr__(self, "reference_price", ReferencePrice(self.reference_price))
        object.__setattr__(self, "bar_inclusion", BarInclusion(self.bar_inclusion))
        if self.confirmation is not None:
            # A wait window the tracking budget cannot cover would leave "confirmed?"
            # permanently unanswerable, so the two are required to be compatible here
            # rather than producing an ambiguous record later.
            if self.confirmation.max_wait_seconds > self.max_tracking_seconds:
                raise ForwardOutcomeError(
                    f"confirmation max_wait_seconds {self.confirmation.max_wait_seconds}s "
                    f"exceeds max_tracking_seconds {self.max_tracking_seconds}s"
                )

    # -- identity ---------------------------------------------------------------
    def to_dict(self) -> dict[str, Any]:
        return {
            "spec_id": self.spec_id,
            "horizons_seconds": list(self.horizons_seconds),
            "max_tracking_seconds": self.max_tracking_seconds,
            "excursion_units": list(self.excursion_units),
            "tick_size": self.tick_size,
            "reference_price": self.reference_price.value,
            "bar_inclusion": self.bar_inclusion.value,
            "session": self.session,
            "session_end_censoring": bool(self.session_end_censoring),
            "max_gap_seconds": self.max_gap_seconds,
            "path_quality": bool(self.path_quality),
            "epsilon": self.epsilon,
            "diagnostic_levels_atr": list(self.diagnostic_levels_atr),
            "ordered_barriers": [b.to_dict() for b in self.ordered_barriers],
            "confirmation": self.confirmation.to_dict() if self.confirmation else None,
            "direction_convention": self.direction_convention,
        }

    @property
    def spec_sha256(self) -> str:
        return canonical_sha256(self.to_dict())

    @property
    def max_tracking_ns(self) -> int:
        return int(self.max_tracking_seconds) * NS

    @property
    def uses_atr(self) -> bool:
        return "atr" in self.excursion_units

    def outcome_columns(self) -> Tuple[str, ...]:
        """The exact, ordered forward-outcome schema implied by this spec."""
        return build_outcome_columns(self)


@dataclass(frozen=True)
class ProposedEntry:
    """One immutable observation anchor.

    Every field is knowable at ``decision_ts``/``entry_ts``. The dataclass is frozen and
    the derived ``entry_sha256`` covers all of it, so an entry set cannot be silently
    re-anchored after its outcomes have been measured.
    """

    study_id: str
    source_period: str
    candidate_key: str
    decision_ts: int
    entry_ts: int
    direction: Direction
    entry_price: float
    reference_price: ReferencePrice
    authorization_sha256: str
    source_freeze_sha256: str
    entry_id: str = ""
    regime_id: Optional[str] = None
    entry_atr: Optional[float] = None
    model_id: Optional[str] = None
    model_hash: Optional[str] = None
    score: Optional[float] = None
    score_decile: Optional[int] = None
    threshold_id: Optional[str] = None
    maturity_bucket: Optional[str] = None
    maturity_seconds: Optional[float] = None
    session_close_ts: Optional[int] = None
    selector_id: Optional[str] = None
    metadata: Tuple[Tuple[str, Any], ...] = field(default_factory=tuple)

    def __post_init__(self) -> None:
        object.__setattr__(self, "direction", Direction(self.direction))
        object.__setattr__(self, "reference_price", ReferencePrice(self.reference_price))
        object.__setattr__(self, "decision_ts", int(self.decision_ts))
        object.__setattr__(self, "entry_ts", int(self.entry_ts))
        object.__setattr__(self, "entry_price", float(self.entry_price))
        if isinstance(self.metadata, Mapping):
            object.__setattr__(self, "metadata", tuple(sorted(self.metadata.items())))
        else:
            object.__setattr__(self, "metadata", tuple(self.metadata or ()))
        if self.entry_ts < self.decision_ts:
            raise ForwardOutcomeError(
                f"entry_ts {self.entry_ts} precedes decision_ts {self.decision_ts}"
            )
        if not (self.entry_price > 0):
            raise ForwardOutcomeError("entry_price must be a positive finite price")
        if self.entry_atr is not None and not (float(self.entry_atr) > 0):
            raise ForwardOutcomeError("entry_atr must be positive when supplied")
        if not self.entry_id:
            object.__setattr__(self, "entry_id", self._derive_entry_id())

    def _derive_entry_id(self) -> str:
        # Deterministic and collision-safe across selectors: two selectors may anchor on
        # the same candidate, and they must produce distinct entries rather than silently
        # de-duplicating to one.
        return canonical_sha256({
            "study_id": self.study_id,
            "source_period": self.source_period,
            "candidate_key": self.candidate_key,
            "decision_ts": self.decision_ts,
            "entry_ts": self.entry_ts,
            "direction": self.direction.value,
            "model_id": self.model_id,
            "threshold_id": self.threshold_id,
            "selector_id": self.selector_id,
        })[:32]

    def to_dict(self) -> dict[str, Any]:
        body = asdict(self)
        body["direction"] = self.direction.value
        body["reference_price"] = self.reference_price.value
        body["metadata"] = {k: v for k, v in self.metadata}
        return body

    def to_row(self) -> dict[str, Any]:
        """Flat parquet row; nested metadata is JSON-encoded for a stable schema."""
        import json

        body = self.to_dict()
        body["metadata"] = json.dumps(body["metadata"], sort_keys=True, default=str)
        body["entry_sha256"] = self.entry_sha256
        return body

    @property
    def entry_sha256(self) -> str:
        return canonical_sha256(self.to_dict())


# ---------------------------------------------------------------------------
# Schema generation
# ---------------------------------------------------------------------------

def horizon_label(seconds: int) -> str:
    return f"{int(seconds)}s"


def level_label(level: float) -> str:
    text = f"{float(level):g}".replace(".", "p").replace("-", "neg")
    return f"{text}atr"


_UNIT_SUFFIX = {"points": "", "atr": "_atr", "ticks": "_ticks"}

ENTRY_IDENTITY_COLUMNS: Tuple[str, ...] = (
    "entry_id", "candidate_key", "study_id", "source_period", "regime_id",
    "decision_ts", "entry_ts", "direction", "entry_price", "entry_atr",
    "model_id", "model_hash", "score", "score_decile", "threshold_id",
    "maturity_bucket", "maturity_seconds", "selector_id",
)

OBSERVATION_STATE_COLUMNS: Tuple[str, ...] = (
    "outcome_status", "censor_reason", "resolved_at_ts", "tracked_seconds",
    "bars_observed", "first_bar_ts", "last_bar_ts", "max_gap_seconds_observed",
)

PROVENANCE_COLUMNS: Tuple[str, ...] = (
    "spec_sha256", "entry_sha256", "authorization_sha256", "source_freeze_sha256",
)


def _excursion_columns(prefix: str, spec: ForwardOutcomeSpec) -> list[str]:
    return [f"{prefix}{_UNIT_SUFFIX[u]}" for u in spec.excursion_units]


def build_outcome_columns(spec: ForwardOutcomeSpec) -> Tuple[str, ...]:
    """Derive the full ordered outcome schema from a spec.

    This function is the single authority for what a forward-outcome table contains.
    Persistence, the causal guard and the analysis layer all read it, so a spec change
    propagates to all three instead of drifting between them.
    """
    cols: list[str] = list(ENTRY_IDENTITY_COLUMNS)

    if spec.confirmation is not None:
        cols += ["confirmed", "confirmation_ts", "seconds_to_confirmation", "confirmation_price"]

    for h in spec.horizons_seconds:
        lab = horizon_label(h)
        cols += _excursion_columns(f"mfe_{lab}", spec)
        cols += _excursion_columns(f"mae_{lab}", spec)
        cols += _excursion_columns(f"return_{lab}", spec)
        cols += [f"time_to_mfe_{lab}", f"time_to_mae_{lab}", f"price_{lab}", f"status_{lab}"]
        if spec.path_quality:
            cols += [
                f"mfe_mae_ratio_{lab}", f"return_over_mae_{lab}", f"mfe_minus_mae_{lab}",
                f"retained_mfe_fraction_{lab}", f"giveback_from_mfe_{lab}",
            ]

    cols += _excursion_columns("max_mfe", spec)
    cols += _excursion_columns("max_mae", spec)
    cols += _excursion_columns("final_return", spec)
    cols += ["time_to_max_mfe", "time_to_max_mae", "final_price"]
    if spec.path_quality:
        cols += [
            "max_mfe_mae_ratio", "final_return_over_mae", "max_mfe_minus_max_mae",
            "retained_mfe_fraction_final", "giveback_from_max_mfe",
        ]

    for level in spec.diagnostic_levels_atr:
        lab = level_label(level)
        cols += [
            f"time_to_favorable_{lab}", f"time_to_adverse_{lab}",
            f"favorable_before_adverse_{lab}", f"first_touch_ambiguous_{lab}",
        ]

    for barrier in spec.ordered_barriers:
        prefix = f"ordered_{barrier.barrier_id}"
        cols += [
            f"{prefix}_disposition", f"{prefix}_binary_label",
            f"{prefix}_favorable_touch_ts", f"{prefix}_adverse_touch_ts",
            f"{prefix}_time_to_favorable", f"{prefix}_time_to_adverse",
            f"{prefix}_first_touch_ambiguous", f"{prefix}_censor_reason",
            f"{prefix}_resolved_at_ts",
        ]

    if spec.confirmation is not None:
        cols += _excursion_columns("pre_confirmation_mfe", spec)
        cols += _excursion_columns("pre_confirmation_mae", spec)
        cols += _excursion_columns("post_confirmation_mfe", spec)
        cols += _excursion_columns("post_confirmation_mae", spec)
        cols += [
            "pre_confirmation_time_to_mfe", "pre_confirmation_time_to_mae",
            "post_confirmation_time_to_mfe", "post_confirmation_time_to_mae",
            "post_confirmation_status",
        ]
        for h in spec.confirmation.post_horizons_seconds:
            lab = horizon_label(h)
            cols += _excursion_columns(f"post_confirmation_return_{lab}", spec)
            cols += [f"post_confirmation_status_{lab}"]

    cols += list(OBSERVATION_STATE_COLUMNS)
    cols += list(PROVENANCE_COLUMNS)

    seen: set[str] = set()
    ordered: list[str] = []
    for col in cols:
        if col in seen:
            raise ForwardOutcomeError(f"duplicate generated outcome column: {col}")
        seen.add(col)
        ordered.append(col)
    return tuple(ordered)
