"""Bespoke Study Type Compiler (Escape Hatch).
============================================
Enforces full repository governance, timestamp contracts, and preflight integration
while allowing custom implementation code with mandatory machine-readable justification.
"""

from __future__ import annotations

from typing import Any, Dict, List
from research.schemas.study_spec import StudySpec
from research.study_types.base import BaseStudyCompiler, CompileResult, FitDecision
from research.engines.population_engine import compile_population_contract
from research.engines.target_engine import compile_target_contract
from research.engines.feature_binding_engine import compile_feature_contract
from research.engines.timestamp_engine import compile_timestamp_contract
from research.engines.lineage_engine import validate_lineage
from research.engines.baseline_engine import validate_baseline


class BespokeStudyCompiler(BaseStudyCompiler):
    """Compiler for bespoke studies with mandatory justification."""

    def evaluate_fit(self, spec: StudySpec) -> FitDecision:
        return FitDecision.BESPOKE_REQUIRED

    def compile(self, spec: StudySpec) -> CompileResult:
        fit = self.evaluate_fit(spec)
        spec_hash = spec.compute_sha256()

        if not spec.bespoke or not spec.bespoke.reason or len(spec.bespoke.reason.strip()) < 10:
            raise ValueError(
                "BESPOKE_JUSTIFICATION_REJECTED: 'bespoke.reason' must be substantive (>=10 chars), "
                "explaining why canonical study types cannot express the research intent."
            )

        pop_contract = compile_population_contract(spec.population, spec.instrument)
        target_contract = compile_target_contract(spec.target)
        feat_contract = compile_feature_contract(spec.features)
        ts_contract = compile_timestamp_contract(spec.instrument.symbol)
        lineage_info = validate_lineage(spec)
        baseline_info = validate_baseline(spec.baseline)

        strategy_class = spec.execution.strategy_class or "studies.bespoke.CustomStrategy"
        exec_contract = {
            "runtime": "nautilustrader",
            "strategy_class": strategy_class,
            "bounded_execution": spec.execution.bounded,
            "progress_seconds": spec.execution.progress_seconds,
            "checkpoint": spec.execution.checkpoint,
            "custom_scope": spec.bespoke.custom_scope or ["implementation/custom_logic.py"],
            "chronology": {
                "train": spec.chronology.train or [],
                "dev": spec.chronology.dev or [],
                "diagnostic": spec.chronology.diagnostic or [],
                "prohibited": spec.chronology.prohibited or [],
            },
        }

        contracts = {
            "population_contract": pop_contract,
            "target_contract": target_contract,
            "feature_contract": feat_contract,
            "execution_contract": exec_contract,
            "timestamp_contract": ts_contract,
            "lineage": lineage_info,
            "baseline": baseline_info,
            "bespoke_justification": {
                "reason": spec.bespoke.reason,
                "unsupported_contract_element": spec.bespoke.unsupported_contract_element,
                "canonical_type_considered": spec.bespoke.canonical_type_considered,
                "reusable_extension_considered": spec.bespoke.reusable_extension_considered,
                "custom_scope": spec.bespoke.custom_scope,
            },
        }

        spec_md = self._render_spec_md(spec, spec_hash, contracts)
        task_packet = self._render_task_packet(spec, spec_hash, contracts)
        test_declarations = self._build_test_declarations(spec, contracts)
        summary_card = self._build_summary_card(spec, fit, contracts)

        return CompileResult(
            fit_decision=fit,
            study_id=spec.study.id,
            study_type=spec.study.type,
            spec_sha256=spec_hash,
            contracts=contracts,
            nt_strategy_class=strategy_class,
            test_declarations=test_declarations,
            rendered_spec_md=spec_md,
            rendered_task_packet=task_packet,
            summary_card=summary_card,
            custom_code_allowed=True,
        )

    def _render_spec_md(self, spec: StudySpec, spec_hash: str, contracts: Dict[str, Any]) -> str:
        b = spec.bespoke
        return f"""# SPEC: {spec.study.id} (BESPOKE ESCAPE HATCH)

**Generated by Study Factory (Bespoke)**  
**Source `study.yaml` SHA-256:** `{spec_hash}`  
**Risk Tier:** `{spec.study.risk_tier}`  
**Execution Runtime:** `NautilusTrader` (`{contracts['execution_contract']['strategy_class']}`)

---

## 1. Bespoke Justification

- **Reason:** {b.reason}
- **Unsupported Element:** `{b.unsupported_contract_element}`
- **Canonical Considered:** `{b.canonical_type_considered or 'None'}`
- **Custom Scope:** `{b.custom_scope or ['implementation/']}`

---

## 2. Research Objective

{spec.study.description}

---

## 3. Causal Timing & Invariants

All bespoke code MUST inherit:
1. `FULL_BAR_OHLCV_AVAILABLE_ONLY_AT_INTERVAL_CLOSE`
2. `latest_source_availability_ts <= observation_ts`
3. NautilusTrader as the sole execution engine.
"""

    def _render_task_packet(self, spec: StudySpec, spec_hash: str, contracts: Dict[str, Any]) -> Dict[str, Any]:
        return {
            "task_packet_version": "1.0",
            "study_id": spec.study.id,
            "study_type": "bespoke",
            "spec_sha256": spec_hash,
            "risk_tier": spec.study.risk_tier,
            "runtime": "nautilustrader",
            "strategy_class": contracts["execution_contract"]["strategy_class"],
            "contracts": contracts,
            "preflight_required": True,
            "preflight_status": "PENDING_EXECUTION",
        }

    def _build_test_declarations(self, spec: StudySpec, contracts: Dict[str, Any]) -> List[Dict[str, Any]]:
        return [
            {
                "name": "test_nautilustrader_runtime_invariant",
                "runtime": "nautilustrader",
            },
            {
                "name": "test_bespoke_justification_non_empty",
                "reason": spec.bespoke.reason,
            },
        ]

    def _build_summary_card(self, spec: StudySpec, fit: FitDecision, contracts: Dict[str, Any]) -> str:
        b = spec.bespoke
        return f"""======================================================================
STUDY COMPILED: {spec.study.id} [BESPOKE]
======================================================================
Type: bespoke
Fit: {fit.value}
Operation: {spec.operation.kind}
Runtime: NautilusTrader
Strategy: {contracts['execution_contract']['strategy_class']}

Bespoke Reason:
  {b.reason}
Unsupported Element:
  {b.unsupported_contract_element}

Custom Scope:
  {b.custom_scope or ['implementation/']}

Preflight eligibility:
  CLEAR (Pre-execution audit required for bespoke code)
======================================================================"""
