"""Generic phase-zero authorization for declarative studies.

The manifest is generated by ``scripts/build_phase0_manifest.py`` from the
compiled study's explicit canonical FeatureInstances.  No study module is
imported and no historical collector/alias catalog is consulted here.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any


def _manifest_hash(body: dict[str, Any]) -> str:
    return hashlib.sha256(json.dumps(body, indent=2).encode("utf-8")).hexdigest()


def authorize_execution(manifest_path: Path, *, feature_authority: str = "active") -> dict[str, Any]:
    """Return a verified generic phase-zero manifest or fail closed."""
    if not manifest_path.is_file():
        raise RuntimeError("phase-zero authorization missing; collection and fit are refused")
    try:
        observed = json.loads(manifest_path.read_text(encoding="utf-8"))
    except Exception as exc:  # pragma: no cover - defensive boundary
        raise RuntimeError("PHASE0_MANIFEST_INVALID: unreadable JSON") from exc
    if observed.get("authenticated") is not True:
        raise RuntimeError("PHASE0_MANIFEST_UNAUTHENTICATED")
    observed_authority = observed.get("feature_authority", "active")
    if observed_authority != feature_authority:
        raise RuntimeError("FEATURE_AUTHORITY_PROPAGATION_MISMATCH")
    recorded = observed.get("manifest_sha256")
    body = dict(observed)
    body.pop("manifest_sha256", None)
    if not recorded or recorded != _manifest_hash(body):
        raise RuntimeError("PHASE0_MANIFEST_STALE_OR_ALTERED")
    return observed
