"""FeatureSnapshotBuilder — builds immutable snapshot rows.

Workflow on every snapshot:

  1. registry.audit_provenance(decision_ts)   # raises if violation
  2. Read state per TF from registry only
  3. Compute features purely from registry state
  4. Emit one frozen FeatureSnapshot row with provenance columns

Snapshot rows include for every TF (30s/1m/3m/5m):
  - last_<tf>_close_ts        (close time of latest closed bar)
  - last_<tf>_open_ts         (open time of latest closed bar)
  - regime_<tf>               (+1 / -1 / 0)
  - bars_in_regime_<tf>
  - atr_<tf>
  - close_<tf>                (last completed bar's close price)
  - dist_close_to_ema3_h_<tf>_atr   (price distance feature)
  - dist_close_to_ema9_h_<tf>_atr
  - dist_close_to_ema3_l_<tf>_atr
  - dist_close_to_ema9_l_<tf>_atr

Provenance proof:
  - decision_ts
  - bar_ts_event   (the triggering bar's OPEN time, if any)
  - kind           (snapshot type tag, e.g. "regime_flip", "bar1_check")
  - last_<tf>_close_ts <= decision_ts for all TFs (audit-checked)

Snapshots are frozen (immutable). They are appended to a sink list
that the strategy writes to parquet at on_stop().
"""

from __future__ import annotations
from dataclasses import dataclass, asdict
from typing import Any, Optional

from .registry import (
    CompletedBarRegistry, CompletedBarState, SUPPORTED_TIMEFRAMES,
)


@dataclass(frozen=True)
class FeatureSnapshot:
    """One snapshot row. Immutable. Generated by
    FeatureSnapshotBuilder.build()."""
    # ---- Provenance ----
    decision_ts: int
    bar_ts_event: int          # ts_event of the triggering bar
    kind: str                  # "regime_flip" / "bar1_check" / "checkpoint" / etc.
    event_id: int              # monotonic per-snapshot id
    direction: int             # +1 / -1 / 0 (per kind; e.g. signal direction at flip)

    # ---- Provenance — per-TF close_ts proofs ----
    last_30s_close_ts: int
    last_1m_close_ts: int
    last_3m_close_ts: int
    last_5m_close_ts: int

    # ---- Per-TF state (30s) ----
    regime_30s: int
    bars_in_regime_30s: int
    atr_30s: float
    close_30s: float
    dist_close_to_ema3_h_30s_atr: float
    dist_close_to_ema9_h_30s_atr: float
    dist_close_to_ema3_l_30s_atr: float
    dist_close_to_ema9_l_30s_atr: float

    # ---- Per-TF state (1m) ----
    regime_1m: int
    bars_in_regime_1m: int
    atr_1m: float
    close_1m: float
    dist_close_to_ema3_h_1m_atr: float
    dist_close_to_ema9_h_1m_atr: float
    dist_close_to_ema3_l_1m_atr: float
    dist_close_to_ema9_l_1m_atr: float

    # ---- Per-TF state (3m) ----
    regime_3m: int
    bars_in_regime_3m: int
    atr_3m: float
    close_3m: float
    dist_close_to_ema3_h_3m_atr: float
    dist_close_to_ema9_h_3m_atr: float
    dist_close_to_ema3_l_3m_atr: float
    dist_close_to_ema9_l_3m_atr: float

    # ---- Per-TF state (5m) ----
    regime_5m: int
    bars_in_regime_5m: int
    atr_5m: float
    close_5m: float
    dist_close_to_ema3_h_5m_atr: float
    dist_close_to_ema9_h_5m_atr: float
    dist_close_to_ema3_l_5m_atr: float
    dist_close_to_ema9_l_5m_atr: float

    # ---- Optional event-specific extras ----
    flip_bar_h: float = float("nan")
    flip_bar_l: float = float("nan")
    flip_bar_c: float = float("nan")
    flip_direction: int = 0
    bar1_h: float = float("nan")        # bar+1 high (bar1_check)
    bar1_l: float = float("nan")
    bar1_o: float = float("nan")
    bar1_c: float = float("nan")
    hhll_ok: bool = False               # HH/LL confirmation passed?
    momentum_ok: bool = False           # close-direction passed?
    confirmed: bool = False             # both?
    became_trade: bool = False          # set after entry submission
    # path_checkpoint fields (only set when kind == "path_checkpoint")
    trade_event_id: int = -1            # event_id of the entry snapshot
    trade_direction: int = 0
    trade_fill_price: float = float("nan")
    trade_fill_ts: int = 0
    trade_atr_at_signal: float = float("nan")
    elapsed_s: float = float("nan")
    cur_pnl_atr: float = float("nan")
    cur_mfe_atr: float = float("nan")
    cur_mae_atr: float = float("nan")
    cur_giveback_atr: float = float("nan")
    cur_close_price: float = float("nan")

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def _features_per_tf(s: CompletedBarState) -> dict:
    """Compute the per-TF feature block for one timeframe."""
    atr = s.atr if s.atr == s.atr else 0.0  # NaN -> 0 for safety
    safe_atr = atr if atr > 0 else 1.0
    return {
        "regime": s.regime,
        "bars_in_regime": s.bars_in_regime,
        "atr": s.atr,
        "close": s.close,
        "dist_close_to_ema3_h_atr":
            (s.close - s.ema3_h) / safe_atr,
        "dist_close_to_ema9_h_atr":
            (s.close - s.ema9_h) / safe_atr,
        "dist_close_to_ema3_l_atr":
            (s.close - s.ema3_l) / safe_atr,
        "dist_close_to_ema9_l_atr":
            (s.close - s.ema9_l) / safe_atr,
    }


class FeatureSnapshotBuilder:
    """Builds FeatureSnapshot rows from the registry.

    Construct with the shared registry. Call build() inside the
    strategy at every decision/snapshot moment. The builder calls
    audit_provenance() FIRST — any violation raises and aborts.
    """

    def __init__(self, registry: CompletedBarRegistry):
        self._registry = registry
        self._next_event_id = 0

    def build(
        self,
        *,
        decision_ts: int,
        bar_ts_event: int,
        kind: str,
        direction: int = 0,
        # Optional event-specific extras
        flip_bar_h: float = float("nan"),
        flip_bar_l: float = float("nan"),
        flip_bar_c: float = float("nan"),
        flip_direction: int = 0,
        bar1_h: float = float("nan"),
        bar1_l: float = float("nan"),
        bar1_o: float = float("nan"),
        bar1_c: float = float("nan"),
        hhll_ok: bool = False,
        momentum_ok: bool = False,
        confirmed: bool = False,
        # path_checkpoint extras
        trade_event_id: int = -1,
        trade_direction: int = 0,
        trade_fill_price: float = float("nan"),
        trade_fill_ts: int = 0,
        trade_atr_at_signal: float = float("nan"),
        elapsed_s: float = float("nan"),
        cur_pnl_atr: float = float("nan"),
        cur_mfe_atr: float = float("nan"),
        cur_mae_atr: float = float("nan"),
        cur_giveback_atr: float = float("nan"),
        cur_close_price: float = float("nan"),
    ) -> Optional[FeatureSnapshot]:
        """Build a snapshot. Returns None ONLY if the registry has
        not yet seen at least one bar in every required TF (warmup
        period). Otherwise audits provenance (raises on violation)
        then returns the frozen snapshot."""
        # Warmup gate
        states = {tf: self._registry.get(tf)
                    for tf in SUPPORTED_TIMEFRAMES}
        if any(s is None for s in states.values()):
            return None

        # HARD INVARIANT — raises CausalityViolation on violation
        self._registry.audit_provenance(decision_ts)

        eid = self._next_event_id
        self._next_event_id += 1

        s30 = states["30s"]; s1 = states["1m"]
        s3 = states["3m"]; s5 = states["5m"]
        f30 = _features_per_tf(s30); f1 = _features_per_tf(s1)
        f3 = _features_per_tf(s3); f5 = _features_per_tf(s5)

        return FeatureSnapshot(
            decision_ts=int(decision_ts),
            bar_ts_event=int(bar_ts_event),
            kind=kind,
            event_id=eid,
            direction=int(direction),
            last_30s_close_ts=int(s30.close_ts),
            last_1m_close_ts=int(s1.close_ts),
            last_3m_close_ts=int(s3.close_ts),
            last_5m_close_ts=int(s5.close_ts),
            # 30s
            regime_30s=int(f30["regime"]),
            bars_in_regime_30s=int(f30["bars_in_regime"]),
            atr_30s=float(f30["atr"]),
            close_30s=float(f30["close"]),
            dist_close_to_ema3_h_30s_atr=float(
                f30["dist_close_to_ema3_h_atr"]),
            dist_close_to_ema9_h_30s_atr=float(
                f30["dist_close_to_ema9_h_atr"]),
            dist_close_to_ema3_l_30s_atr=float(
                f30["dist_close_to_ema3_l_atr"]),
            dist_close_to_ema9_l_30s_atr=float(
                f30["dist_close_to_ema9_l_atr"]),
            # 1m
            regime_1m=int(f1["regime"]),
            bars_in_regime_1m=int(f1["bars_in_regime"]),
            atr_1m=float(f1["atr"]),
            close_1m=float(f1["close"]),
            dist_close_to_ema3_h_1m_atr=float(
                f1["dist_close_to_ema3_h_atr"]),
            dist_close_to_ema9_h_1m_atr=float(
                f1["dist_close_to_ema9_h_atr"]),
            dist_close_to_ema3_l_1m_atr=float(
                f1["dist_close_to_ema3_l_atr"]),
            dist_close_to_ema9_l_1m_atr=float(
                f1["dist_close_to_ema9_l_atr"]),
            # 3m
            regime_3m=int(f3["regime"]),
            bars_in_regime_3m=int(f3["bars_in_regime"]),
            atr_3m=float(f3["atr"]),
            close_3m=float(f3["close"]),
            dist_close_to_ema3_h_3m_atr=float(
                f3["dist_close_to_ema3_h_atr"]),
            dist_close_to_ema9_h_3m_atr=float(
                f3["dist_close_to_ema9_h_atr"]),
            dist_close_to_ema3_l_3m_atr=float(
                f3["dist_close_to_ema3_l_atr"]),
            dist_close_to_ema9_l_3m_atr=float(
                f3["dist_close_to_ema9_l_atr"]),
            # 5m
            regime_5m=int(f5["regime"]),
            bars_in_regime_5m=int(f5["bars_in_regime"]),
            atr_5m=float(f5["atr"]),
            close_5m=float(f5["close"]),
            dist_close_to_ema3_h_5m_atr=float(
                f5["dist_close_to_ema3_h_atr"]),
            dist_close_to_ema9_h_5m_atr=float(
                f5["dist_close_to_ema9_h_atr"]),
            dist_close_to_ema3_l_5m_atr=float(
                f5["dist_close_to_ema3_l_atr"]),
            dist_close_to_ema9_l_5m_atr=float(
                f5["dist_close_to_ema9_l_atr"]),
            flip_bar_h=float(flip_bar_h),
            flip_bar_l=float(flip_bar_l),
            flip_bar_c=float(flip_bar_c),
            flip_direction=int(flip_direction),
            bar1_h=float(bar1_h),
            bar1_l=float(bar1_l),
            bar1_o=float(bar1_o),
            bar1_c=float(bar1_c),
            hhll_ok=bool(hhll_ok),
            momentum_ok=bool(momentum_ok),
            confirmed=bool(confirmed),
            trade_event_id=int(trade_event_id),
            trade_direction=int(trade_direction),
            trade_fill_price=float(trade_fill_price),
            trade_fill_ts=int(trade_fill_ts),
            trade_atr_at_signal=float(trade_atr_at_signal),
            elapsed_s=float(elapsed_s),
            cur_pnl_atr=float(cur_pnl_atr),
            cur_mfe_atr=float(cur_mfe_atr),
            cur_mae_atr=float(cur_mae_atr),
            cur_giveback_atr=float(cur_giveback_atr),
            cur_close_price=float(cur_close_price),
        )
