#!/usr/bin/env python3
"""Create Study CLI Tool.
======================
Scaffolds a new research study directory, renders authoritative contracts,
and generates derived deterministic tests from study.yaml.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
import yaml

# Ensure project root in python path
project_root = Path(__file__).parent.parent.resolve()
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from research.schemas.study_spec import StudySpec
from research.study_types.flip_prediction import FlipPredictionCompiler
from research.study_types.bespoke import BespokeStudyCompiler
from research.study_types.base import FitDecision


def parse_study_spec_from_yaml(yaml_path: Path) -> StudySpec:
    if not yaml_path.exists():
        raise FileNotFoundError(f"Configuration file not found: {yaml_path}")
    with open(yaml_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    return StudySpec.model_validate(data)


def get_compiler_for_spec(spec: StudySpec):
    if spec.study.type == "flip_prediction":
        return FlipPredictionCompiler()
    elif spec.study.type == "bespoke":
        return BespokeStudyCompiler()
    else:
        raise ValueError(f"UNSUPPORTED_STUDY_TYPE: {spec.study.type}")


def materialize_compile_result(spec: StudySpec, result, study_dir: Path, *, write_study_yaml: bool = False) -> dict:
    """Write the complete canonical derived-artifact set from one compile result."""
    study_dir.mkdir(parents=True, exist_ok=True)
    if write_study_yaml:
        with open(study_dir / "study.yaml", "w", encoding="utf-8") as f:
            yaml.safe_dump(spec.model_dump(exclude_none=True, mode="json"), f, sort_keys=False)
    (study_dir / "SPEC.md").write_text(result.rendered_spec_md, encoding="utf-8")
    (study_dir / "TASK_PACKET.json").write_text(json.dumps(result.rendered_task_packet, indent=2), encoding="utf-8")
    compiled = {"study_id": spec.study.id, "study_type": spec.study.type, "spec_sha256": result.spec_sha256,
                "spec": spec.model_dump(mode="json"), "contracts": result.contracts, "strategy_class": result.nt_strategy_class}
    (study_dir / "compiled_study.json").write_text(json.dumps(compiled, indent=2), encoding="utf-8")
    config = study_dir / "config"; config.mkdir(exist_ok=True)
    for name, contract in result.contracts.items():
        (config / f"{name}.json").write_text(json.dumps(contract, indent=2), encoding="utf-8")
    tests = study_dir / "tests"; tests.mkdir(exist_ok=True)
    (tests / "test_study_contracts.py").write_text(generate_test_file_content(spec, result), encoding="utf-8")
    return {"spec_sha256": result.spec_sha256, "contracts": result.contracts}


def materialize_compiled_study(spec: StudySpec, study_dir: Path, *, write_study_yaml: bool = False) -> dict:
    """Compile once, then write only canonical derived StudySpec artifacts."""
    compiler = get_compiler_for_spec(spec)
    from research.engines.timestamp_engine import compile_with_timestamp_evidence_adapter
    result = compile_with_timestamp_evidence_adapter(compiler, spec, study_dir)
    return materialize_compile_result(spec, result, study_dir, write_study_yaml=write_study_yaml)


def generate_test_file_content(spec: StudySpec, result) -> str:
    """Renders study contract tests that load real artifacts and can actually fail.

    The previous generator baked every value into *both* sides of its assertions --
    ``assert "nautilustrader" == "nautilustrader"``, and an expected SHA compared against
    the same literal. Those tests passed unconditionally and would have kept passing if
    every artifact in the study had drifted or been deleted.

    Each test below loads at least one artifact from disk at run time and compares it to
    an independently derived value, so drift between `study.yaml`, `compiled_study.json`,
    the config contracts and the feature registry makes them fail.
    """
    return f'''"""Auto-Generated Deterministic Study Contract Tests.
===================================================
Derived from study.yaml (SHA-256: {result.spec_sha256}).

Generated by scripts/create_study.py. Every assertion below reads an artifact from disk
and compares it against an independently recomputed value. Nothing is compared to a baked
literal on both sides -- a generated test that cannot fail is worse than no test, because
it reports coverage it does not provide.
"""

import hashlib
import json
from pathlib import Path

import pytest
import yaml

STUDY_DIR = Path(__file__).resolve().parents[1]

# The repository root is located by walking up from this file until a marker is found,
# then falling back to the installed package location. Deriving it positionally
# (STUDY_DIR.parents[1]) breaks whenever a study is scaffolded outside studies/ -- the
# tests then silently resolve module paths inside a temp directory.
def _repo_root() -> Path:
    for candidate in [STUDY_DIR, *STUDY_DIR.parents]:
        if (candidate / "features" / "registry.py").exists() and (candidate / "research").is_dir():
            return candidate
    import features
    return Path(features.__file__).resolve().parents[1]


REPO_ROOT = _repo_root()


def _study_yaml():
    return yaml.safe_load((STUDY_DIR / "study.yaml").read_text(encoding="utf-8"))


def _compiled():
    return json.loads((STUDY_DIR / "compiled_study.json").read_text(encoding="utf-8"))


def _config(name):
    return json.loads((STUDY_DIR / "config" / f"{{name}}.json").read_text(encoding="utf-8"))


def test_runtime_is_nautilustrader_in_every_authority():
    """The runtime declared by study.yaml, the compiled spec and the execution contract agree."""
    assert _study_yaml()["execution"]["runtime"] == "nautilustrader"
    assert _compiled()["spec"]["execution"]["runtime"] == "nautilustrader"
    assert _config("execution_contract")["runtime"] == "nautilustrader"


def test_compiled_spec_hash_matches_recomputed_spec_hash():
    """compiled_study.json's spec_sha256 is reproducible from the spec it contains."""
    import sys
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    from research.schemas.study_spec import StudySpec

    compiled = _compiled()
    respec = StudySpec.model_validate(_study_yaml())
    assert respec.compute_sha256() == compiled["spec_sha256"], (
        "study.yaml no longer compiles to the spec hash recorded in compiled_study.json"
    )


def test_feature_hash_equals_hash_recomputed_from_the_ordered_list():
    """The frozen feature hash is derived from the declared ordered list, not asserted."""
    fc = _config("feature_contract")
    declared = fc["feature_list"] or []
    recomputed = hashlib.sha256(json.dumps(declared).encode("utf-8")).hexdigest()
    assert fc["feature_list_sha256"] == recomputed
    assert fc["feature_count"] == len(declared)
    # When study.yaml declares features via `instances`, the compiler echoes the
    # resolved ordered list onto StudySpec.features.feature_list. A train-only
    # candidate-universe study legitimately leaves it None. Compare only when set.
    spec_feature_list = _compiled()["spec"]["features"].get("feature_list")
    if spec_feature_list is not None:
        assert spec_feature_list == declared


def test_declared_features_resolve_in_the_central_registry():
    """Every declared feature binds to a real registry entry with a real implementation."""
    import sys
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    from features.registry import resolve_feature_request

    fc = _config("feature_contract")
    # `feature_list` entries are rendered physical output columns; the canonical
    # identity to resolve is (canonical_name, parameters) from resolved_feature_instances.
    resolved_instances = fc.get("resolved_feature_instances")
    if resolved_instances:
        items = [(r["canonical_name"], r.get("parameters") or {{}}) for r in resolved_instances]
    else:
        items = [(n, {{}}) for n in (fc.get("feature_list") or [])]
    import importlib
    for canonical, params in items:
        resolved = resolve_feature_request(canonical, params)
        impl = resolved["provider"]
        assert impl, f"{{canonical!r}} has no implementation binding"
        module_name = impl.rsplit(".", 1)[0]
        mod = importlib.import_module(module_name)
        assert Path(mod.__file__).exists(), (
            f"{{canonical!r}} implementation module {{module_name}} does not resolve to a file"
        )


def test_population_contract_matches_the_authoritative_study_population():
    """The compiled population contract equals what study.yaml declares."""
    y = _study_yaml()["population"]
    pc = _config("population_contract")
    assert pc["prevailing_regime"] == y.get("prevailing_regime")
    assert pc["session"] == y.get("session")
    assert pc["population_type"] == y.get("type")
    assert _compiled()["spec"]["population"]["session"] == pc["session"]


def test_session_resolves_to_an_explicit_window():
    """`RTH` is not self-explanatory; it must resolve to concrete boundaries."""
    import sys
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    from utils.session_boundaries import resolve_session_window

    session = _config("population_contract")["session"]
    start, end = resolve_session_window(session)
    assert start < end


def test_target_contract_fields_equal_the_compiled_target():
    """Target fields agree across study.yaml, the compiled spec and the config contract."""
    y = _study_yaml()["target"]
    tc = _config("target_contract")
    # A `flip` target authors horizon_seconds directly. A composite ordered-barrier
    # target carries it on its single forward outcome; the compiler surfaces that one
    # value onto target_contract.horizon_seconds. Either way the contract must equal it.
    fo_horizons = {{fo.get("horizon_seconds") for fo in (tc.get("required_forward_outcomes") or [])}}
    fo_horizons.discard(None)
    if y.get("horizon_seconds") is not None:
        expected_h = y["horizon_seconds"]
    elif len(fo_horizons) == 1:
        expected_h = next(iter(fo_horizons))
    else:
        expected_h = None
    assert tc["horizon_seconds"] == expected_h
    assert tc["direction"] == y.get("direction")
    assert tc["event"] == (y.get("event") or "regime_flip")
    compiled_h = _compiled()["spec"]["target"].get("horizon_seconds")
    if compiled_h is not None:
        assert compiled_h == tc["horizon_seconds"]


def test_censoring_policy_is_declared_and_bounded_by_the_horizon():
    """A declared censoring policy must be internally consistent with the horizon."""
    tc = _config("target_contract")
    policy = tc.get("censoring_policy")
    assert policy is not None, "target contract declares no censoring policy"
    # The censoring bound is the effective horizon (legacy default 300 when a target
    # declares none anywhere).
    assert policy["max_horizon_seconds"] == (tc["horizon_seconds"] or 300)


def test_execution_chronology_equals_the_source_decision():
    """The compiled chronology equals study.yaml's, and the partitions stay disjoint."""
    y = _study_yaml()["chronology"]
    ec = _config("execution_contract")["chronology"]
    assert ec["train"] == (y.get("train") or [])
    assert ec["dev"] == (y.get("dev") or [])
    assert ec["prohibited"] == (y.get("prohibited") or [])
    assert set(ec["train"]).isdisjoint(ec["dev"])
    assert set(ec["train"]).isdisjoint(ec["prohibited"])
    assert set(ec["dev"]).isdisjoint(ec["prohibited"])


def test_timestamp_evidence_is_measured_on_this_study_instrument():
    """The timestamp contract must carry this instrument's own empirical measurements."""
    symbol = _study_yaml()["instrument"]["symbol"].upper()
    tsc = _config("timestamp_contract")
    measurement = tsc["nautilus_catalog"]["empirical_measurement"]
    assert measurement["status"] == "MEASURED"
    measured = measurement["measurements"]
    assert measured, "no bar-timestamp measurements were recorded"
    for bar_type, rec in measured.items():
        assert bar_type.upper().startswith(symbol + "."), (
            f"timestamp evidence for {{bar_type}} does not belong to instrument {{symbol}}"
        )
        assert rec["pass"] is True
        assert rec["observed_deltas_ns"] == [rec["expected_delta_ns"]]


def test_deliverables_are_declared_per_mode_and_all_reachable():
    """Every declared deliverable maps to a producer in a mode this study may run."""
    import sys
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    from research.engines.deliverables_engine import KNOWN_ARTIFACT_PRODUCERS, artifact_modes

    dc = _config("deliverables_contract")
    assert dc["authorized_modes"], "no authorized modes declared"
    for mode, artifacts in dc["deliverables_by_mode"].items():
        assert mode in dc["authorized_modes"]
        assert artifacts, f"mode {{mode}} declares no deliverables"
        for a in artifacts:
            assert a in KNOWN_ARTIFACT_PRODUCERS, f"{{a}} has no known producer"
            assert mode in artifact_modes(a), (
                f"{{a}} is declared under {{mode}} but produced by {{artifact_modes(a)}}"
            )


def test_spec_md_renders_the_deliverables_contract():
    """SPEC prose and the machine-readable contract cannot drift apart."""
    spec_md = (STUDY_DIR / "SPEC.md").read_text(encoding="utf-8")
    dc = _config("deliverables_contract")
    for artifacts in dc["deliverables_by_mode"].values():
        for a in artifacts:
            assert a in spec_md, f"deliverable {{a}} is in the contract but not in SPEC.md"
'''


def create_study(config_path: Path, output_dir: Path = Path("studies")) -> int:
    try:
        spec = parse_study_spec_from_yaml(config_path)
    except Exception as e:
        print(f"[ERROR] Invalid study configuration in {config_path}: {e}", file=sys.stderr)
        return 1

    compiler = get_compiler_for_spec(spec)
    try:
        result = compiler.compile(spec)
    except Exception as e:
        print(f"[ERROR] Study compilation failed: {e}", file=sys.stderr)
        return 1

    study_dir = output_dir / spec.study.id
    config_dir = study_dir / "config"
    impl_dir = study_dir / "implementation"
    tests_dir = study_dir / "tests"
    checkpoints_dir = study_dir / "checkpoints"
    results_dir = study_dir / "results"
    artifacts_dir = study_dir / "artifacts"
    audit_dir = study_dir / "audit"

    # Create directory tree
    for d in [study_dir, config_dir, impl_dir, tests_dir, checkpoints_dir, results_dir, artifacts_dir, audit_dir]:
        d.mkdir(parents=True, exist_ok=True)

    # 1. Write study.yaml
    study_yaml_dest = study_dir / "study.yaml"
    with open(study_yaml_dest, "w", encoding="utf-8") as f:
        yaml.dump(spec.model_dump(exclude_none=True), f, sort_keys=False)

    # 2. Write SPEC.md
    with open(study_dir / "SPEC.md", "w", encoding="utf-8") as f:
        f.write(result.rendered_spec_md)

    # 3. Write TASK_PACKET.json
    with open(study_dir / "TASK_PACKET.json", "w", encoding="utf-8") as f:
        json.dump(result.rendered_task_packet, f, indent=2)

    # 4. Write compiled_study.json
    compiled_data = {
        "study_id": spec.study.id,
        "study_type": spec.study.type,
        "spec_sha256": result.spec_sha256,
        "spec": spec.model_dump(),
        "contracts": result.contracts,
        "strategy_class": result.nt_strategy_class,
    }
    with open(study_dir / "compiled_study.json", "w", encoding="utf-8") as f:
        json.dump(compiled_data, f, indent=2)

    # 5. Write individual config JSON files
    for name, c_dict in result.contracts.items():
        with open(config_dir / f"{name}.json", "w", encoding="utf-8") as f:
            json.dump(c_dict, f, indent=2)

    # 6. Write derived test file
    test_file_content = generate_test_file_content(spec, result)
    with open(tests_dir / "test_study_contracts.py", "w", encoding="utf-8") as f:
        f.write(test_file_content)

    print(result.summary_card)
    print(f"\nSuccessfully created study scaffolding at: {study_dir}")
    return 0


def main():
    parser = argparse.ArgumentParser(description="Create and scaffold a study from study.yaml")
    parser.add_argument("--config", type=str, required=True, help="Path to study.yaml")
    parser.add_argument("--out-dir", type=str, default="studies", help="Root directory for studies (default: studies)")
    args = parser.parse_args()

    sys.exit(create_study(Path(args.config), Path(args.out_dir)))


if __name__ == "__main__":
    main()
